/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./views/Appmine copy 2/index.vue')['default']
    AboutView: typeof import('./views/AboutView.vue')['default']
    App: typeof import('./App.vue')['default']
    Appcart: typeof import('./views/Appcart/index.vue')['default']
    AppDetail: typeof import('./views/AppDetail/index.vue')['default']
    AppList: typeof import('./views/AppList/index.vue')['default']
    Applogin: typeof import('./views/Applogin/index.vue')['default']
    Appmain: typeof import('./views/Appmain/index.vue')['default']
    Appmine: typeof import('./views/Appmine/index.vue')['default']
    Banner: typeof import('./views/Appmain/banner.vue')['default']
    CommonFool: typeof import('./components/commonFool.vue')['default']
    Commonnav: typeof import('./components/commonnav.vue')['default']
    ConmonList: typeof import('./components/conmonList.vue')['default']
    copy: typeof import('./views/Appregister/step_two copy.vue')['default']
    Demo: typeof import('./components/Demo.vue')['default']
    Grid: typeof import('./views/Appmain/grid.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    Notfound: typeof import('./views/notfound/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step_one: typeof import('./views/Appregister/step_one.vue')['default']
    Step_three: typeof import('./views/Appregister/step_three.vue')['default']
    Step_two: typeof import('./views/Appregister/step_two.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
